site:
  site_name: 'Zona Brokers'
  site_title: 'Zona Brokers'
  home_title: 'Tenemos un lugar para vos'

  # Select style:

  # Header: 1 o 2
  header_style: '2'
  # Footer: 1, 2 o 3
  footer_style: '2'
  # Home banner: 1, 2 o 3
  home_banner_style: '3'
  # Miniaturas de propiedades: 1, 2 y 3
  property_box_style: '1'
  # Titulos de la home: 1 o 2
  home_titles_style: '2'
  # Ficha : 1, 2, 3 o 4
  property_details_style: '1'
  # Pagina Empresa: 1 o 2
  about_page_style: '2'
  # Pagina Brokers: 1
  brokers_page_style: '1'
  # Botones: 1, 2, 3, 4 o 5
  buttons_style: '1'

  # Select display (true o false):

  display_contact_page: true
  display_brokers_page: true
  display_blog_page: false
  blog_id: '824175598138027203'
  display_about_page: true
  display_projects: true
  display_terrains: false
  display_home_carousel: true
  display_ads_banners: false
  display_links_box: false
  display_agency_section: false
  display_newsletter: true
  display_link_box_image: false
  display_continue_search: false
  display_street_view: false

  # Select set (true o false)
  set_og_tags: true

  # Group Properties @ listing
  group_properties: true

  # Secondary Color
  secondary_color: '#F7A800'
